"""Експорт TestSuite: JSON, CSV Standard, Zephyr Scale CSV, TestRail CSV.

Новий формат = функція + запис у _EXPORTERS (і значення в ExportFormat).
Назви колонок Zephyr/TestRail відповідають їхнім шаблонам; під час імпорту обидві системи
все одно показують майстер зіставлення колонок, де це можна виправити.
"""
import csv
import io
from collections.abc import Callable, Iterable
from dataclasses import dataclass

from app.schemas import ExportFormat, TestCase, TestSuite

_FORMULA_PREFIXES = ("=", "+", "-", "@", "\t", "\r")

# У Zephyr Scale за замовчуванням пріоритети High / Normal / Low (Critical немає).
_ZEPHYR_PRIORITY = {"Critical": "High", "High": "High", "Medium": "Normal", "Low": "Low"}


@dataclass(frozen=True)
class ExportResult:
    content: bytes
    media_type: str
    extension: str


def _csv_safe(value: str) -> str:
    """Захист від CSV/Formula Injection: комірка, що починається з = + - @, екранується апострофом."""
    return f"'{value}" if value[:1] in _FORMULA_PREFIXES else value


def _csv_result(header: list[str], rows: Iterable[list[str]]) -> ExportResult:
    """Єдина точка запису CSV: тут санітизуються ВСІ комірки, забути про це неможливо."""
    buffer = io.StringIO()
    writer = csv.writer(buffer, lineterminator="\r\n")
    writer.writerow(header)
    writer.writerows([_csv_safe(cell) for cell in row] for row in rows)
    # utf-8-sig (BOM): Excel коректно відкриває кирилицю.
    return ExportResult(buffer.getvalue().encode("utf-8-sig"), "text/csv; charset=utf-8", "csv")


def _to_json(suite: TestSuite) -> ExportResult:
    return ExportResult(suite.model_dump_json(indent=2).encode("utf-8"), "application/json", "json")


def _to_csv_standard(suite: TestSuite) -> ExportResult:
    """Один тест-кейс = один рядок, кроки в одній комірці з нумерацією."""
    header = ["ID", "Title", "Type", "Priority", "Preconditions", "Steps", "Test Data", "Expected Result"]
    rows = []
    for tc in suite.test_cases:
        steps = "\n".join(f"{i}. {step}" for i, step in enumerate(tc.steps, start=1))
        rows.append([
            tc.id, tc.title, tc.test_type.value, tc.priority.value,
            tc.preconditions, steps, tc.test_data, tc.expected_result,
        ])
    return _csv_result(header, rows)


def _step_positions(tc: TestCase):
    """Для формату «один крок - один рядок»: (крок, це перший крок?, це останній крок?)."""
    last = len(tc.steps) - 1
    for i, step in enumerate(tc.steps):
        yield step, i == 0, i == last


def _to_zephyr(suite: TestSuite) -> ExportResult:
    """Zephyr Scale: поля кейса - у першому рядку, решта рядків містять лише кроки."""
    header = ["Test Case Name", "Objective", "Precondition", "Status", "Priority",
              "Step", "Test Data", "Expected Result"]
    rows = []
    for tc in suite.test_cases:
        for step, first, last in _step_positions(tc):
            rows.append([
                tc.title if first else "",
                f"{tc.test_type.value} scenario. Generated by Req2Test" if first else "",
                tc.preconditions if first else "",
                "Draft" if first else "",  # згенеровано AI -> спершу рев'ю, потім Approved
                _ZEPHYR_PRIORITY[tc.priority.value] if first else "",
                step,
                tc.test_data if first else "",
                tc.expected_result if last else "",  # очікуваний результат - на останньому кроці
            ])
    return _csv_result(header, rows)


def _to_testrail(suite: TestSuite) -> ExportResult:
    """TestRail (шаблон Test Case Steps): поля кейса - у першому рядку, далі рядки кроків."""
    header = ["Title", "Section", "Type", "Priority", "Preconditions",
              "Steps (Step)", "Steps (Expected Result)"]
    rows = []
    for tc in suite.test_cases:
        for step, first, last in _step_positions(tc):
            # У TestRail немає окремого поля тестових даних у кроку: кладемо їх у перший крок.
            step_text = f"{step}\n\nTest data: {tc.test_data}" if first and tc.test_data else step
            rows.append([
                tc.title if first else "",
                "Req2Test" if first else "",
                "Functional" if first else "",
                tc.priority.value if first else "",  # Low/Medium/High/Critical - як у TestRail
                tc.preconditions if first else "",
                step_text,
                tc.expected_result if last else "",
            ])
    return _csv_result(header, rows)


_EXPORTERS: dict[ExportFormat, Callable[[TestSuite], ExportResult]] = {
    ExportFormat.JSON: _to_json,
    ExportFormat.CSV: _to_csv_standard,
    ExportFormat.ZEPHYR: _to_zephyr,
    ExportFormat.TESTRAIL: _to_testrail,
}


def export_suite(suite: TestSuite, fmt: ExportFormat) -> ExportResult:
    return _EXPORTERS[fmt](suite)
