"""Экспорт TestSuite: JSON, CSV Standard, Zephyr Scale CSV, TestRail CSV.

Новый формат = функция + запись в _EXPORTERS (и значение в ExportFormat).
Названия колонок Zephyr/TestRail соответствуют их шаблонам; при импорте обе системы
всё равно показывают мастер сопоставления колонок, где это можно поправить.
"""
import csv
import io
from collections.abc import Callable, Iterable
from dataclasses import dataclass

from app.schemas import ExportFormat, TestCase, TestSuite

_FORMULA_PREFIXES = ("=", "+", "-", "@", "\t", "\r")

# У Zephyr Scale по умолчанию приоритеты High / Normal / Low (Critical нет).
_ZEPHYR_PRIORITY = {"Critical": "High", "High": "High", "Medium": "Normal", "Low": "Low"}


@dataclass(frozen=True)
class ExportResult:
    content: bytes
    media_type: str
    extension: str


def _csv_safe(value: str) -> str:
    """Защита от CSV/Formula Injection: ячейка, начинающаяся с = + - @, экранируется апострофом."""
    return f"'{value}" if value[:1] in _FORMULA_PREFIXES else value


def _csv_result(header: list[str], rows: Iterable[list[str]]) -> ExportResult:
    """Единая точка записи CSV: здесь санитизируются ВСЕ ячейки, забыть про это нельзя."""
    buffer = io.StringIO()
    writer = csv.writer(buffer, lineterminator="\r\n")
    writer.writerow(header)
    writer.writerows([_csv_safe(cell) for cell in row] for row in rows)
    # utf-8-sig (BOM): Excel корректно открывает кириллицу.
    return ExportResult(buffer.getvalue().encode("utf-8-sig"), "text/csv; charset=utf-8", "csv")


def _to_json(suite: TestSuite) -> ExportResult:
    return ExportResult(suite.model_dump_json(indent=2).encode("utf-8"), "application/json", "json")


def _to_csv_standard(suite: TestSuite) -> ExportResult:
    """Один тест-кейс = одна строка, шаги в одной ячейке с нумерацией."""
    header = ["ID", "Title", "Type", "Priority", "Preconditions", "Steps", "Test Data", "Expected Result"]
    rows = []
    for tc in suite.test_cases:
        steps = "\n".join(f"{i}. {step}" for i, step in enumerate(tc.steps, start=1))
        rows.append([
            tc.id, tc.title, tc.test_type.value, tc.priority.value,
            tc.preconditions, steps, tc.test_data, tc.expected_result,
        ])
    return _csv_result(header, rows)


def _step_positions(tc: TestCase):
    """Для формата «один шаг - одна строка»: (шаг, это первый шаг?, это последний шаг?)."""
    last = len(tc.steps) - 1
    for i, step in enumerate(tc.steps):
        yield step, i == 0, i == last


def _to_zephyr(suite: TestSuite) -> ExportResult:
    """Zephyr Scale: поля кейса - в первой строке, остальные строки содержат только шаги."""
    header = ["Test Case Name", "Objective", "Precondition", "Status", "Priority",
              "Step", "Test Data", "Expected Result"]
    rows = []
    for tc in suite.test_cases:
        for step, first, last in _step_positions(tc):
            rows.append([
                tc.title if first else "",
                f"{tc.test_type.value} scenario. Generated by Req2Test" if first else "",
                tc.preconditions if first else "",
                "Draft" if first else "",  # сгенерировано AI -> сначала ревью, потом Approved
                _ZEPHYR_PRIORITY[tc.priority.value] if first else "",
                step,
                tc.test_data if first else "",
                tc.expected_result if last else "",  # ожидаемый результат - на последнем шаге
            ])
    return _csv_result(header, rows)


def _to_testrail(suite: TestSuite) -> ExportResult:
    """TestRail (шаблон Test Case Steps): поля кейса - в первой строке, далее строки шагов."""
    header = ["Title", "Section", "Type", "Priority", "Preconditions",
              "Steps (Step)", "Steps (Expected Result)"]
    rows = []
    for tc in suite.test_cases:
        for step, first, last in _step_positions(tc):
            # В TestRail нет отдельного поля тестовых данных у шага: кладём их в первый шаг.
            step_text = f"{step}\n\nTest data: {tc.test_data}" if first and tc.test_data else step
            rows.append([
                tc.title if first else "",
                "Req2Test" if first else "",
                "Functional" if first else "",
                tc.priority.value if first else "",  # Low/Medium/High/Critical - как в TestRail
                tc.preconditions if first else "",
                step_text,
                tc.expected_result if last else "",
            ])
    return _csv_result(header, rows)


_EXPORTERS: dict[ExportFormat, Callable[[TestSuite], ExportResult]] = {
    ExportFormat.JSON: _to_json,
    ExportFormat.CSV: _to_csv_standard,
    ExportFormat.ZEPHYR: _to_zephyr,
    ExportFormat.TESTRAIL: _to_testrail,
}


def export_suite(suite: TestSuite, fmt: ExportFormat) -> ExportResult:
    return _EXPORTERS[fmt](suite)
